spring:
  h2:
    console:
      enabled: true
#      settings:
#        trace: true
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database: h2
    show-sql: true
#    properties:
#      hibernate:
#        '[format_sql]': true

  datasource:
    url: jdbc:h2:mem:h2db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
  data:
    rest:
      default-page-size: 20
      max-page-size: 1000

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  level:
    root: info
    '[com.shiva]': debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{5}.%M - %msg%n'